# Generated by Django 3.2.4 on 2021-06-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_actortypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.actortypes', verbose_name='Тип'),
        ),
    ]
