# Generated by Django 3.2.4 on 2021-07-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_actor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ganre',
            new_name='genre',
        ),
    ]
